version: "3.8"

services:
  # sut Automated Repository Test
  # see https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build: .
    command: ["/bin/sh", "-c", "which bash && which fping && which macchanger && which nc && which ngrep && which nmap && which netstat && which libressl && which drill && which curl && which git && which find && which wrk && which wrk2 && which vegeta && which http && which fortio && testssl.sh"]
